redis:
  image: redis
  container_name: cache
  ports:
    - 6379:6379

mongodb:
  image: mongo:4.2
  container_name: mongodb
  ports:
    - 27017:27017

rabbit:
  image: "rabbitmq:3-management"
  container_name: rabbit
  environment:
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"